server.port=8080

# DB Connection - ticketing_concert \uC2A4\uD0A4\uB9C8 \uC0AC\uC6A9
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.124.100:33066/ticketing_concert?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# \uC5D4\uB4DC\uD3EC\uC778\uD2B8 \uB178\uCD9C (Prometheus\uC640 Health \uCCB4\uD06C)
management.endpoints.web.exposure.include=prometheus,health

# \uC0C1\uC138\uD55C \uD5EC\uC2A4 \uCCB4\uD06C \uC815\uBCF4 \uD45C\uC2DC (\uC7A5\uC560 \uB514\uBC84\uAE45 \uC6A9\uB3C4)
management.endpoint.health.show-details=always

# \uD504\uB85C\uBA54\uD14C\uC6B0\uC2A4 \uC5D4\uB4DC\uD3EC\uC778\uD2B8 \uD65C\uC131\uD654
management.endpoint.prometheus.enabled=true

# \uBAA8\uB4E0 \uBA54\uD2B8\uB9AD\uC5D0 \uC5B4\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984 \uD0DC\uADF8 \uCD94\uAC00 (Grafana \uD544\uD130\uB9C1 \uCD5C\uC801\uD654)
management.metrics.tags.application=${MANAGEMENT_METRICS_TAGS_APPLICATION:concert-service}

# Redis Connection (Mini PC 101\uBC88\uC9C0)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:192.168.124.101}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}

# (\uC120\uD0DD) \uCEE4\uB125\uC158 \uD480 \uC124\uC815: \uB300\uADDC\uBAA8 \uD2B8\uB798\uD53D \uB300\uBE44
spring.data.redis.lettuce.pool.max-active=20
spring.data.redis.lettuce.pool.max-idle=10